development:
  adapter: postgresql
  encoding: unicode
  database: my_app_development
  pool: 5
  username: my_app
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: my_app_test
  pool: 5
  username: my_app
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: d474qgg1plq7jp
  pool: 5
  username: xrdtbugqvgpfpr
  password: OCE5RNwMSFVF36BKqeLhVk-JEa